import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const catalogs = Object.fromEntries(['en', 'nl'].map((locale) => [locale, JSON.parse(readFileSync(new URL(`../frontend/src/locales/${locale}.json`, import.meta.url), 'utf8'))]))

export async function privacyWorkflow(page, origin, root, password, axe) {
  for (const locale of ['en', 'nl']) {
    const t = (key) => catalogs[locale][key] ?? (() => { throw new Error(`Missing privacy QA translation: ${key}`) })()
    const button = (key) => page.getByRole('button', { name: t(key), exact: true })
    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.getByRole('combobox', { name: 'Language / Taal' }).selectOption(locale)
    await page.getByRole('link', { name: t('Prospects'), exact: true }).click()
    await button('Add prospect').click()
    const add = page.getByRole('dialog', { name: t('Add prospect') })
    await add.getByLabel(t('Name'), { exact: true }).fill(`Fictional Privacy ${locale}`)
    await add.getByLabel(t('Source URL')).fill(`https://simbi.com/fictional-privacy-qa-${locale}`)
    await add.getByRole('button', { name: t('Add prospect'), exact: true }).click()
    await add.waitFor({ state: 'hidden' })
    const before = await (await page.request.get(`${origin}/api/export`)).json()
    await page.getByRole('link', { name: t('Settings'), exact: true }).click()
    await page.getByRole('heading', { name: t('Privacy & cleanup') }).waitFor()
    await page.getByLabel(t('Keep inactive contact history for (days)')).fill('90')
    await button('Save retention preference').click()
    await page.getByText(t('Retention preference saved. No personal records were automatically deleted.')).waitFor()
    await button('Preview cleanup').click()
    await page.getByText(t('No contacts in this preview will be removed.')).waitFor()
    if (await button('Review removal').isEnabled()) throw new Error('Empty cleanup allowed removal')
    await button('Discard preview').click()
    await page.getByLabel(t('Cleanup scope')).selectOption('prospect')
    await page.getByLabel(t('Search contacts for removal')).fill(`Fictional Privacy ${locale}`)
    await button('Find contacts').click()
    const select = page.getByLabel(t('Contact to remove'))
    await select.getByRole('option', { name: new RegExp(`Fictional Privacy ${locale}`) }).waitFor({ state: 'attached' })
    const selectedId = await select.getByRole('option', { name: new RegExp(`Fictional Privacy ${locale}`) }).getAttribute('value')
    await select.selectOption(selectedId)
    await button('Preview cleanup').click()
    await page.getByRole('heading', { name: t('Removal preview') }).waitFor()
    await button('Review removal').click()
    let dialog = page.getByRole('dialog', { name: t('Confirm local removal') })
    await dialog.waitFor()
    if (await dialog.evaluate((element) => { const rect = element.getBoundingClientRect(); return rect.left < -1 || rect.right > innerWidth + 1 || Math.abs(rect.left - (innerWidth - rect.width) / 2) > 2 })) throw new Error('Desktop cleanup dialog is clipped or off center')
    await dialog.getByLabel(t('Local account password')).fill(password)
    await dialog.getByRole('checkbox').check()
    await page.screenshot({ path: resolve(root, '..', `simbi-privacy-${locale}-desktop.png`) })
    await page.keyboard.press('Escape')
    await dialog.waitFor({ state: 'hidden' })
    if (!(await button('Review removal').evaluate((element) => document.activeElement === element))) throw new Error('Cleanup cancel did not restore focus')
    const afterCancel = await (await page.request.get(`${origin}/api/export`)).json()
    for (const table of ['prospects', 'drafts', 'handoffs', 'replies', 'reminders', 'suppressions']) {
      if (JSON.stringify(before[table]) !== JSON.stringify(afterCancel[table])) throw new Error(`Cleanup preview/cancel mutated ${table}`)
    }
    await button('Review removal').click()
    dialog = page.getByRole('dialog', { name: t('Confirm local removal') })
    if (await dialog.getByLabel(t('Local account password')).inputValue() !== '' || await dialog.getByRole('checkbox').isChecked()) throw new Error('Cancelled removal retained secrets or acknowledgement')
    await page.setViewportSize({ width: 390, height: 450 })
    if (await dialog.evaluate((element) => { const rect = element.getBoundingClientRect(); return rect.left < -1 || rect.right > innerWidth + 1 || rect.top < -1 || rect.bottom > innerHeight + 1 })) throw new Error('Mobile cleanup dialog exceeds viewport bounds')
    await page.screenshot({ path: resolve(root, '..', `simbi-privacy-${locale}-mobile.png`) })
    await page.addScriptTag({ content: axe.source })
    const findings = await page.evaluate(async () => window.axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'] } }))
    if (findings.violations.length) throw new Error(`Cleanup ${locale} accessibility: ${JSON.stringify(findings.violations.map(({ id, nodes }) => ({ id, targets: nodes.map(({ target }) => target) })))}`)
    if (await dialog.evaluate((element) => element.scrollWidth > element.clientWidth + 1)) throw new Error('Cleanup dialog has horizontal overflow')
    await dialog.getByRole('checkbox').check()
    await dialog.getByLabel(t('Local account password')).fill(password)
    await dialog.getByRole('button', { name: t('Confirm removal'), exact: true }).click()
    await dialog.waitFor({ state: 'hidden' })
    await page.getByText(new RegExp(locale === 'nl' ? 'Herstelbestand:' : 'Recovery file:')).waitFor()
    const after = await (await page.request.get(`${origin}/api/export`)).json()
    if (after.prospects.some(({ id }) => id === Number(selectedId)) || after.prospects.length !== before.prospects.length - 1) throw new Error('Cleanup did not remove exactly selected fictional contact')
    if (!after.suppressions.some(({ normalized_value, prospect_id }) => normalized_value === `simbi:https://simbi.com/fictional-privacy-qa-${locale}` && prospect_id === null)) throw new Error('Cleanup lost do-not-contact identity')
    for (const table of ['campaigns', 'templates', 'drafts', 'handoffs', 'replies', 'reminders']) {
      if (JSON.stringify(before[table]) !== JSON.stringify(after[table])) throw new Error(`Selected-contact cleanup modified unrelated ${table}`)
    }
    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.reload({ waitUntil: 'networkidle' })
    await button('Check cleanup receipts').click()
    await page.getByText(new RegExp(locale === 'nl' ? 'Herstelbestand:' : 'Recovery file:')).first().waitFor()
    const receipts = await (await page.request.get(`${origin}/api/privacy/receipts`)).json()
    if (receipts.items.length !== (locale === 'en' ? 1 : 2)) throw new Error('Cleanup receipts did not survive reload')
    const receipt = receipts.items.find(({ counts }) => counts.prospects === 1)
    if (!receipt?.backup_file) throw new Error('Missing cleanup backup receipt')
  }
  await page.getByRole('combobox', { name: 'Language / Taal' }).selectOption('en')
}
